// Shared firmware state passed between the FreeRTOS tasks.
//
// The navigation loop owns the FSM; the other tasks only submit inputs and read
// snapshots, so the shared surface is deliberately tiny and lock-free where it
// matters (a single critical section on the latest position, and a mutex only
// around the status snapshot used for telemetry).
#pragma once

#include <Arduino.h>

#include "app_config.hpp"
#include "navigation/navigation_fsm.hpp"
#include "position_provider.hpp"
#include "telemetry.hpp"

namespace firmware {

/// Configuration embedded in the firmware image.
///
/// The graph and the navigation parameters are compiled in so the device can
/// boot and navigate without a filesystem or a server.  Both documents use the
/// same schema as config/graph.json and config/navigation.json, so the values
/// can be regenerated by the tooling in scripts/.
struct BuiltinConfig {
    const char* graph_json;
    const char* navigation_json;
};

/// The default development map (12 nodes, 12 x 8 m Smart Market grid).
const char* builtinGraphJson();

/// The default navigation parameters (mirrors config/navigation.json).
const char* builtinNavigationJson();

/// Everything the tasks share.
struct FirmwareContext {
    /// Navigation state machine (owned by the navigation task).
    nav::NavigationFsm fsm{};

    /// Latest accepted position (written by the position task).
    LatestPosition latest_position{};

    /// Serialised access to the FSM status for telemetry formatting.
    SemaphoreHandle_t status_mutex{nullptr};

    /// Telemetry publisher (owned by the telemetry task).
    TelemetryPublisher* telemetry{nullptr};

    /// Set by the command task, consumed by the navigation task.
    volatile bool command_stop{false};
    volatile bool command_cancel{false};
    volatile bool command_estop{false};
    volatile bool command_clear_estop{false};
    volatile bool command_replan{false};
    volatile int command_destination{-1};

    /// Set by the navigation task so the command task can report readiness.
    volatile bool navigation_ready{false};

    /// Counters for diagnostics.
    volatile uint32_t position_samples{0};
    volatile uint32_t position_rejected{0};
    volatile uint32_t loop_overruns{0};
};

/// Single global context (avoids heap allocation during start-up).
FirmwareContext& context();

}  // namespace firmware
